/// Flutter icons InboxNavigationIcons
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InboxNavigationIcons
///      fonts:
///       - asset: fonts/InboxNavigationIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class InboxNavigationIcons {
  InboxNavigationIcons._();

  static const _kFontFam = 'InboxNavigationIcons';
  static const String? _kFontPkg = null;

  static const IconData ChatIcon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData HomeIcon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData NotificationIcon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData ProfileIcon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData SearchIcon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData StoryIcon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
