// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDURqTMwNNSw0-wgdP6bXqBejokLgz7Nxs',
    appId: '1:1088073001188:web:f925cc258c421e098724f1',
    messagingSenderId: '1088073001188',
    projectId: 'inbox-d3522',
    authDomain: 'inbox-d3522.firebaseapp.com',
    storageBucket: 'inbox-d3522.appspot.com',
    measurementId: 'G-BSCGJRMKLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI4nmVw3jSUbMlNH2HNATofP9GShiCz10',
    appId: '1:1088073001188:android:eca176e87d5b9cb78724f1',
    messagingSenderId: '1088073001188',
    projectId: 'inbox-d3522',
    storageBucket: 'inbox-d3522.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2E5UT0-rb_ZzYUqjyjhNKohmBHi4Qm2E',
    appId: '1:1088073001188:ios:cb1580bcd1cd679b8724f1',
    messagingSenderId: '1088073001188',
    projectId: 'inbox-d3522',
    storageBucket: 'inbox-d3522.appspot.com',
    iosClientId: '1088073001188-ep1vjdkrd6meo20lradgm9282nj1g91j.apps.googleusercontent.com',
    iosBundleId: 'com.example.inbox',
  );
}
